# Generated by Django 3.0.3 on 2020-02-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=400)),
                ('web_site', models.URLField(default='', max_length=500)),
                ('logo', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=500)),
                ('trim', models.CharField(default='', max_length=500)),
                ('img_url', models.ImageField(default='pic_folder/None/no-img.jpg', max_length=500, upload_to='pic_folder/')),
                ('milage', models.CharField(default='', max_length=500)),
                ('color', models.CharField(default='', max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='auto.Seller')),
            ],
        ),
    ]
