# Generated by Django 3.0.3 on 2020-02-11 17:26

from django.db import migrations

def seed(apps, schema_editor):
    Seller = apps.get_model('auto', 'seller')
    Car = apps.get_model('auto', 'car')
    
    #Sellers
    lujack = Seller(name = "Lujack Auto Plaza", phone = '555-555-5555', address = '100 Brady St, Davenport, Ia 52805', web_site = 'http://lujack.com')
    lujack.save()

    #Cars
    Car(make = "Honda", model = "Civic", trim = "sport", img_url = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTrMZQnh-oQj8MbVX7vwXQdzX1-FHyOI_bscu7QIFXqMGiydkjp", milage = "23000", color = "silver", name = lujack).save()

def fallow(apps, schema_editor):
    Seller = apps.get_model('auto', 'Seller')
    Car = app.get_model('auto', 'Car')
    Seller.objects.all().delete()
    Car.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
