# Generated by Django 3.0.3 on 2020-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20200211_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='web_site',
            field=models.URLField(default='', max_length=100),
        ),
    ]
