# Generated by Django 3.0.3 on 2020-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20200211_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img_url',
            field=models.URLField(default='', max_length=512),
        ),
    ]
